name: PoolParty Deploy

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    
jobs:
  lifeguard:
    if: github.base_ref == 'r2d' || github.base_ref == 'main' || github.base_ref == 'production'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: r2d
    - name: Label this PR with automerge #NOTE(Rejon): This will fail if the PR is from a fork.
      uses: TimonVS/pr-labeler-action@v3.1.0
      with:
        configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        


